### ISSUE TITLE
"There are less than 1 Volume" Error when create

### ISSUE THREAD

**Issue by D1mk0N-CarX** [CarXTechnologies/dro-map-uploader#13]
![image](https://github.com/CarXTechnologies/dro-map-uploader/assets/145037223/66b5f729-79b1-448f-a308-d83c176a9928)

**Comment by D1mk0N-CarX** [comment]
I solved the problem, but you should add a tutorial about global volume profiles, after that I will close the problem

**Comment by Evgenie-Myasnikov** [comment]
Hello! Thanks for feeadback! 
Tutorial is not planned in the near future.
But you can find a tutorial on Unity or Youtube
